version: '3.2'

services:
  user:
    image: "onlinemg"
    container_name: onlinemg
    restart: "no"
    ports:
      - 8080:8080
      - 5005:5005
    tty: true
    logging:
      options:
        max-file: "2"
        max-size: "10m"
    depends_on:
      - db
    build:
      context: .
      dockerfile: "Dockerfile"




  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_MULTIPLE_DATABASES: userdb, productdb
    ports:
      - 5432:5432
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    logging:
      options:
        max-file: "2"
        max-size: "10m"

